/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as PublicCalendarRouteImport } from './routes/_public/calendar'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as PublicShowMediaTypeTmdbIdRouteImport } from './routes/_public/show.$mediaType.$tmdbId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/_public/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCalendarRoute = PublicCalendarRouteImport.update({
  id: '/_public/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicShowMediaTypeTmdbIdRoute =
  PublicShowMediaTypeTmdbIdRouteImport.update({
    id: '/_public/show/$mediaType/$tmdbId',
    path: '/show/$mediaType/$tmdbId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/calendar': typeof PublicCalendarRoute
  '/search': typeof PublicSearchRoute
  '/show/$mediaType/$tmdbId': typeof PublicShowMediaTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/calendar': typeof PublicCalendarRoute
  '/search': typeof PublicSearchRoute
  '/show/$mediaType/$tmdbId': typeof PublicShowMediaTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_public/calendar': typeof PublicCalendarRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/show/$mediaType/$tmdbId': typeof PublicShowMediaTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/profile'
    | '/calendar'
    | '/search'
    | '/show/$mediaType/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/profile'
    | '/calendar'
    | '/search'
    | '/show/$mediaType/$tmdbId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_public/calendar'
    | '/_public/search'
    | '/_public/'
    | '/_public/show/$mediaType/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PublicCalendarRoute: typeof PublicCalendarRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicShowMediaTypeTmdbIdRoute: typeof PublicShowMediaTypeTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/calendar': {
      id: '/_public/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PublicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/show/$mediaType/$tmdbId': {
      id: '/_public/show/$mediaType/$tmdbId'
      path: '/show/$mediaType/$tmdbId'
      fullPath: '/show/$mediaType/$tmdbId'
      preLoaderRoute: typeof PublicShowMediaTypeTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PublicCalendarRoute: PublicCalendarRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicShowMediaTypeTmdbIdRoute: PublicShowMediaTypeTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
